version: "3.5"
services:
  app:
    build:
      dockerfile: "./docker/Dockerfile"
      context: .
    container_name: sosise
    restart: unless-stopped
    ports:
      - "10000:10000"
    volumes:
      - "./.env:/var/www/app/.env"
      - "./cron:/etc/crontabs/root"
      - "./logs:/var/www/app/storage/logs"
      # - /mnt/my_shared_tmpfs:/var/www/app/storage/cache
  redis:
    image: redis:alpine3.20
    container_name: redis
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes
    # Comment if you don't need persistence
    volumes:
      - "./redis:/data"
